### ISSUE TITLE
doesn't work on go > 1.5

### ISSUE THREAD

**Issue by andreyevsyukov** [jvermillard/nativedtls#1]
Hi,

Tried to build your example and get:

../github.com/jvermillard/nativedtls/bio.go:12:10: fatal error: 'internal/bio.h' file not found
# include "internal/bio.h"

How can I find this file?

Thank you in advance.

**Comment by jvermillard** [comment]
you need to download openssl 1.1-pre sources or clone the openssl somewhere: https://github.com/openssl/openssl

Compile it, and make the first line in https://github.com/jvermillard/nativedtls/blob/master/bio.go#L4 point to your openssl sources

and it should work.
Sorry if it's not straight forward, it's really an early PoC

**Comment by andreyevsyukov** [comment]
Thank you for a fast reply!

I did download OpenSSL 1.1, configured and compiled it.
Then changed the bio.go file and now I get:

github.com/jvermillard/nativedtls
In file included from $WORK/github.com/jvermillard/nativedtls/_obj/_cgo_export.c:2:
../github.com/jvermillard/nativedtls/bio.go:86:29: warning: passing 'const char *' to parameter of type 'char *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
../github.com/jvermillard/nativedtls/bio.go:18:53: note: passing argument to parameter 'hint' here
 github.com/jvermillard/nativedtls
../github.com/jvermillard/nativedtls/bio.go:86:29: warning: passing 'const char *' to parameter of type 'char *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
../github.com/jvermillard/nativedtls/bio.go:18:53: note: passing argument to parameter 'hint' here

I compiled with no special options. I did it on my MacBook (Intel CPU), could be that the reason of this issue?

Thank you for any kind of help.

**Comment by jvermillard** [comment]
it's just warninig ? the example should have compiled

**Comment by andreyevsyukov** [comment]
Please see attached full log, it says "exit status 1"
[nativedtls_error.txt](https://github.com/jvermillard/nativedtls/files/281968/nativedtls_error.txt)

**Comment by andreyevsyukov** [comment]
Should I re-compile OpenSSL? I tried "make test" and all tests passed.

Do you have any idea about the issue?

Thank you!

**Comment by jvermillard** [comment]
hmm I don't know I tried only on Linux, I think you should compile differently, like trying dynamic linking and not static linking.
What is the output of the command "pkg-config --libs openssl" on your computer?

Also I think you can try something like (with correct path) :
#cgo LDFLAGS: -L/home/jvermillar/sandbox/openssl/  -lssl -lcrypto
#cgo CFLAGS: -g -Wno-deprecated -I/home/jvermillar/sandbox/openssl/include

and then if it compile, for running the binary: set LD_LIBRARY_PATH= to the pathwith your compiled openssl .so

**Comment by andreyevsyukov** [comment]
Thank you so much for your help!

I changed the "#cgo LDFLAGS" in my bio.go and it compiles now!

Then I try to run it and I get another issue:

In file included from $WORK/github.com/jvermillard/nativedtls/_obj/_cgo_export.c:2:
../github.com/jvermillard/nativedtls/bio.go:86:29: warning: passing 'const char *' to parameter of type 'char *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
../github.com/jvermillard/nativedtls/bio.go:18:53: note: passing argument to parameter 'hint' here

../github.com/jvermillard/nativedtls/bio.go:86:29: warning: passing 'const char *' to parameter of type 'char *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
../github.com/jvermillard/nativedtls/bio.go:18:53: note: passing argument to parameter 'hint' here
panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 1 [running]:
panic(0x4151d20, 0xc82000a5a0)
    /usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/jvermillard/nativedtls._cgoCheckPointer0(0x416f9a0, 0xc820012230, 0xc82000a590, 0x1, 0x1, 0x410ff80)
    ??:0 +0x4d
github.com/jvermillard/nativedtls.NewDTLSClient(0xc820028020, 0x459a310, 0xc820028028, 0x5)
    /Users/ae/go/src/github.com/jvermillard/nativedtls/bio.go:239 +0x44a

So it fails at /bio.go:239 with "C.BIO_set_data(self.bio, unsafe.Pointer(&self))".
I am not really familiar with porting C to Go, so I'm not really sure what this issue is about.

I am so much appreciated for your help and time!

**Comment by jvermillard** [comment]
you changed your LD_LIBRARY_PATH to load the openssl version you compiled and not your system one?

**Comment by andreyevsyukov** [comment]
Hi,

I changed LD_LIBRARY_PATH to my newly compiled OpenSSL. Still the same.

You also asked about pkg-config, here's what I have:

$ pkg-config --libs openssl
-L/usr/local/lib -lssl -lcrypto

**Comment by zubairhamed** [comment]
@jvermillard  Are you using Go v1.5 or less? This issue i think happens in Go 1.6+

Z

**Comment by jvermillard** [comment]
Ah yes, I use Go 1.5 on this laptop
let me upgrade and test again
thanks @zubairhamed

**Comment by zubairhamed** [comment]
@jvermillard  i think its due to the new cgo rules wrt. Sharing of Go pointers vs C pointers in their respective code,

https://feiskyer.github.io/2016/04/19/cgo-in-go-1-6/

**Comment by jvermillard** [comment]
ok I reproduced the problem :)

**Comment by jvermillard** [comment]
after reading the blog post I think I need to recode most of my code :D

**Comment by zubairhamed** [comment]
Aha i suspected that too. I was trying my hand on a fix but ended up going in circles. :-D Had a feeling most of the SSL API calls/code should reside in C.

**Comment by jvermillard** [comment]
should be fixed, found a way to do it without rewriting the whole thing :)

**Comment by andreyevsyukov** [comment]
Hi!

Thank you for finding time for this!
It does compile now for me, with a few warnings but it's ok!

Another problem I get is DTLSClient.Read() returns "0" and empty error. By "empty" I mean it's not nil but err.Error() returns empty string - "".

Please find my example below, the program stops on "Send Data":

`package main

/*
#cgo LDFLAGS: -L/Users/ae/Documents/openssl/ -lssl -lcrypto
#cgo CFLAGS: -g -Wno-deprecated -I/Users/ae/Documents/openssl/include
*/
import "C"

import (
    "fmt"
    "net"
    "io"
    "sync"

```
"github.com/jvermillard/nativedtls"
```

)

func main() {
    nativedtls.Init()

```
ctx := nativedtls.NewDTLSContext()
if !ctx.SetCipherList("PSK-AES256-CCM8:PSK-AES128-CCM8") {
    panic("impossible to set cipherlist")
}

serverAddress, err := net.ResolveUDPAddr("udp", ":5684")
if err != nil {
    panic(err)
}

var wg sync.WaitGroup

wg.Add(1)

go func(){
    fmt.Println("Creating a Server...")

    server, err := net.ListenUDP("udp", serverAddress)
    if err != nil {
        panic(err)
    }

    dtlsServer := nativedtls.NewDTLSClient(ctx, server)
    dtlsServer.SetPSK("Client_identity", []byte("secretPSK"))

    wg.Done()

    buff := make([]byte, 1500)

    for {
        n, err := dtlsServer.Read(buff)
        if err != nil {
            if err == io.EOF {
                panic(err)
            } else {
                continue
            }
        }

        fmt.Println("Server:", string(buff[:n]))

        _, err = dtlsServer.Write(buff)
        if err != nil {
            panic(err)
        }
    }
}()

wg.Wait()

fmt.Println("Creating a Client...")

conn, err := net.DialUDP("udp", nil, serverAddress)
if err != nil {
    panic(err)
}

fmt.Println("...Dialed!")

c := nativedtls.NewDTLSClient(ctx, conn)
c.SetPSK("Client_identity", []byte("secretPSK"))

fmt.Println("Send Data")

n, err := c.Write([]byte("Yeah!\n"))
if err != nil {
    panic(err)
}

fmt.Printf("Data sent: %d \n", n)

buff := make([]byte, 1500)
c.Read(buff)

fmt.Println("Client: ", string(buff))

c.Close()
```

}
`

**Comment by jvermillard** [comment]
on a blocking read, it's behaving correctly. I suppose the other side (server) closed the session and we expect an EOF error?

**Comment by jvermillard** [comment]
when the other side is closing (with tinydtls example it's just by sending a "server:close" message), I receive 0 byte and an EOF error.

Can you provide a server for testing it?
